(maint) fix typos
puppetlabs/puppetlabs-azure pull request #186
Opened 2018-12-27 21:43 UTC by ehom

clean up for localization-friendliness

2019-01-02 19:02 UTC, gguillotte commented
@ehom Looks fine to me from a support perspective but I'll leave docs reviews to @jbondpdx.

2019-01-31 19:26 UTC, jbondpdx requested changes
Looks good to me. One minor change and then good to go!

2019-01-31 19:30 UTC, ehom commented on README.md
> +* Boot diagnostics - Configures the VM `diagnosticsProfile` setting to write out boot diagnostics. If required, manually enable using the portal. Since boot diagnostics only apply at boot time, their
Found one more:

> their most useful

they're most useful

2019-02-01 10:24 UTC, clairecadman approved these changes
I fixed the two typos on line 329

2021-04-15 11:11 UTC, closed without merging